datasets:
  transcripts:
    path: C:\Users\nickz\cuhk_app\docetl\data_sample.json
    type: file
default_model: openai/gpt-5-nano
bypass_cache: true
operations:
- name: truncate_content_head_tail_for_filler
  type: code_map
  code: "def transform(input_doc):\n    content_content = input_doc.get('content',\
    \ '')\n    words = content_content.split()\n\n    if len(words) <= 300:\n    \
    \    # Document is short enough, keep as is\n        truncated = content_content\n\
    \    else:\n        head = ' '.join(words[:200])\n        if 100 > 0:\n      \
    \      tail = ' '.join(words[-100:])\n            truncated = head + ' ... ' +\
    \ tail\n        else:\n            truncated = head\n\n    return {'content':\
    \ truncated}"
- name: extract_filler
  type: code_map
  code: "def transform(input_doc):\n    import re\n    text = input_doc.get('content',\
    \ '') or ''\n    # normalize and lowercase to improve matching\n    normalized\
    \ = ' '.join(text.lower().split())\n    # common filler words and phrases to detect\n\
    \    fillers = ['um','uh','like','you know','i mean','so','actually','basically','right','well','hmm','huh']\n\
    \    # match whole words/phrases using word boundaries\n    pattern = r'\\b(?:um|uh|like|you\
    \ know|i mean|so|actually|basically|right|well|hmm|huh)\\b'\n    matches = re.findall(pattern,\
    \ normalized)\n    # return deterministic, low-cost structured outputs for downstream\
    \ use\n    return {\n        'filler_words': matches,\n        'filler_counts':\
    \ {w: matches.count(w) for w in set(matches)}\n    }\n"
pipeline:
  steps:
  - name: extract_fillers
    input: transcripts
    operations:
    - truncate_content_head_tail_for_filler
    - extract_filler
  output:
    type: file
    path: C:\Users\nickz\cuhk_app\docetl\results\moar_optimization\results1\pipeline_reproduce1_openai_8.json
optimizer_config:
  type: moar
  save_dir: results/moar_optimization/results1
  available_models:
  - openai/gpt-5-mini
  - openai/gpt-5-nano
  evaluation_file: evaluate_fillers.py
  metric_key: filler_extraction_score
  max_iterations: 10
  rewrite_agent_model: openai/gpt-5-mini
  model: openai/gpt-5-mini
rate_limits:
  llm_call:
  - count: 500
    per: 1
    unit: minute
  llm_tokens:
  - count: 500000
    per: 1
    unit: minute
