datasets:
  transcripts:
    path: data_sample.json
    type: file

default_model: openai/gpt-5-mini
bypass_cache: true

operations:
  - name: extract_filler
    type: map
    output:
      schema:
        filler_words: list[str]
    prompt: |
      Extract all instances of filler words spoken in: {{ input.content }}

pipeline:
  steps:
    - name: extract_fillers
      input: transcripts
      operations:
        - extract_filler
  output:
    type: file
    path: results_reproduce1.json

rate_limits:
  llm_call:
    - count: 500
      per: 1
      unit: minute
  llm_tokens:
    - count: 500000
      per: 1
      unit: minute