datasets:
  transcripts:
    path: C:\Users\nickz\cuhk_app\docetl\data_sample.json
    type: file
default_model: openai/gpt-5-nano
bypass_cache: true
operations:
- name: split_extract_measure_words
  type: split
  split_key: content
  method: token_count
  method_kwargs:
    num_tokens: 15000
    model: openai/gpt-5-nano
- name: topk_extract_measure_words_chunks
  type: topk
  method: embedding
  k: 8
  keys:
  - content_chunk
  query: measure words, unit expressions, collective nouns, duration/time expressions,
    quantities, units (e.g., "a drop of", "a flock of", "two minutes", "one minute",
    percent, dollars, people, jobs)
  stratify_key:
  - split_extract_measure_words_id
  embedding_model: text-embedding-3-small
- name: reduce_extract_measure_words
  type: reduce
  reduce_key: split_extract_measure_words_id
  prompt: 'Extract all instances in: the top {{ inputs|length }} most relevant chunks
    from the document (ordered by relevance):

    {% for input in inputs|sort(attribute=''_topk_measure_words_chunks_rank'') %}

    Chunk (Rank {{ input._topk_measure_words_chunks_rank }}, Score {{ input._topk_measure_words_chunks_score
    }}):

    {{ input.content_chunk }}

    {% endfor %}

    where the speaker uses a measure word. These are not numerical words but words
    specifying a unit such as "drop" in the phrase "a drop of water" or "flock" in
    "a flock of geese".

    '
  model: openai/gpt-5-nano
  litellm_completion_kwargs:
    temperature: 0
  output:
    schema:
      measure_words: list[str]
  associative: false
  pass_through: true
pipeline:
  steps:
  - name: extract_measure_words
    input: transcripts
    operations:
    - split_extract_measure_words
    - topk_extract_measure_words_chunks
    - reduce_extract_measure_words
  output:
    type: file
    path: C:\Users\nickz\cuhk_app\docetl\results\moar_optimization\results2\pipeline_reproduce2_openai_2-2-cost.json
optimizer_config:
  type: moar
  save_dir: results/moar_optimization/results2
  available_models:
  - openai/gpt-5-mini
  - openai/gpt-5-nano
  evaluation_file: evaluate_measures.py
  metric_key: measure_extraction_score
  max_iterations: 10
  rewrite_agent_model: openai/gpt-5-mini
  model: openai/gpt-5-mini
rate_limits:
  llm_call:
  - count: 500
    per: 1
    unit: minute
  llm_tokens:
  - count: 500000
    per: 1
    unit: minute
