datasets:
  transcripts:
    path: C:\Users\nickz\cuhk_app\docetl\data_sample.json
    type: file
default_model: openai/gpt-5-nano
bypass_cache: true
operations:
- name: split_extract_measure_words
  type: split
  split_key: content
  method: token_count
  method_kwargs:
    num_tokens: 12000
    model: openai/gpt-5-nano
- name: topk_extract_measure_words_chunks
  type: topk
  method: fts
  k: 5
  keys:
  - content_chunk
  query: measure unit words minute minutes second seconds hour hours day days week
    weeks month months year years percent % people jobs units dollars $ drop flock
    pound pounds ton tons ounce ounces kilogram kilograms
  stratify_key:
  - split_extract_measure_words_id
- name: extract_chunk_measure_words
  type: map
  prompt: 'Extract all instances in: {{ input.content_chunk }} where the speaker uses
    a measure word. These are not numerical words but words specifying a unit such
    as "drop" in the phrase "a drop of water" or "flock" in "a flock of geese". Return
    a JSON array (list) of the exact phrases or words found and nothing else.'
  model: openai/gpt-5-nano
  litellm_completion_kwargs:
    temperature: 0
  output:
    schema:
      chunk_measure_words: string
- name: reduce_extract_measure_words
  type: reduce
  reduce_key: split_extract_measure_words_id
  prompt: 'Combine and deduplicate all measure words extracted from these chunks:

    {% for input in inputs %}

    Chunk measure words: {{ input.chunk_measure_words }}

    {% endfor %}

    Return a single JSON list named "measure_words" containing unique measure words
    found across the document.'
  model: openai/gpt-5-nano
  litellm_completion_kwargs:
    temperature: 0
  output:
    schema:
      measure_words: list[str]
  associative: false
  pass_through: true
pipeline:
  steps:
  - name: extract_measure_words
    input: transcripts
    operations:
    - split_extract_measure_words
    - topk_extract_measure_words_chunks
    - extract_chunk_measure_words
    - reduce_extract_measure_words
  output:
    type: file
    path: C:\Users\nickz\cuhk_app\docetl\results\moar_optimization\results2\pipeline_reproduce2_openai_10.json
optimizer_config:
  type: moar
  save_dir: results/moar_optimization/results2
  available_models:
  - openai/gpt-5-mini
  - openai/gpt-5-nano
  evaluation_file: evaluate_measures.py
  metric_key: measure_extraction_score
  max_iterations: 10
  rewrite_agent_model: openai/gpt-5-mini
  model: openai/gpt-5-mini
rate_limits:
  llm_call:
  - count: 500
    per: 1
    unit: minute
  llm_tokens:
  - count: 500000
    per: 1
    unit: minute
